
package com.co.claro.linenumber;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LineNumberService", targetNamespace = "http://linenumber.claro.co.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LineNumberService {


    /**
     * 
     * @param serial
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLineNumbers", targetNamespace = "http://linenumber.claro.co.com/", className = "com.co.claro.linenumber.GetLineNumbers")
    @ResponseWrapper(localName = "getLineNumbersResponse", targetNamespace = "http://linenumber.claro.co.com/", className = "com.co.claro.linenumber.GetLineNumbersResponse")
    @Action(input = "http://linenumber.claro.co.com/LineNumberService/getLineNumbersRequest", output = "http://linenumber.claro.co.com/LineNumberService/getLineNumbersResponse")
    public List<String> getLineNumbers(
        @WebParam(name = "serial", targetNamespace = "")
        String serial);

}
