
package com.co.claro.linenumber.matriz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceMatrizTelefonia", targetNamespace = "http://matriz.linenumber.claro.co.com/", wsdlLocation = "http://localhost:8080/WSACS/WebServiceMatrizTelefonia?WSDL")
public class WebServiceMatrizTelefonia_Service
    extends Service
{

    private final static URL WEBSERVICEMATRIZTELEFONIA_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEMATRIZTELEFONIA_EXCEPTION;
    private final static QName WEBSERVICEMATRIZTELEFONIA_QNAME = new QName("http://matriz.linenumber.claro.co.com/", "WebServiceMatrizTelefonia");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSACS/WebServiceMatrizTelefonia?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEMATRIZTELEFONIA_WSDL_LOCATION = url;
        WEBSERVICEMATRIZTELEFONIA_EXCEPTION = e;
    }

    public WebServiceMatrizTelefonia_Service() {
        super(__getWsdlLocation(), WEBSERVICEMATRIZTELEFONIA_QNAME);
    }

    public WebServiceMatrizTelefonia_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEMATRIZTELEFONIA_QNAME, features);
    }

    public WebServiceMatrizTelefonia_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEMATRIZTELEFONIA_QNAME);
    }

    public WebServiceMatrizTelefonia_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEMATRIZTELEFONIA_QNAME, features);
    }

    public WebServiceMatrizTelefonia_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceMatrizTelefonia_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceMatrizTelefonia
     */
    @WebEndpoint(name = "WebServiceMatrizTelefoniaPort")
    public WebServiceMatrizTelefonia getWebServiceMatrizTelefoniaPort() {
        return super.getPort(new QName("http://matriz.linenumber.claro.co.com/", "WebServiceMatrizTelefoniaPort"), WebServiceMatrizTelefonia.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceMatrizTelefonia
     */
    @WebEndpoint(name = "WebServiceMatrizTelefoniaPort")
    public WebServiceMatrizTelefonia getWebServiceMatrizTelefoniaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://matriz.linenumber.claro.co.com/", "WebServiceMatrizTelefoniaPort"), WebServiceMatrizTelefonia.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEMATRIZTELEFONIA_EXCEPTION!= null) {
            throw WEBSERVICEMATRIZTELEFONIA_EXCEPTION;
        }
        return WEBSERVICEMATRIZTELEFONIA_WSDL_LOCATION;
    }

}
