
package com.co.claro.linenumber.matriz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceMatrizTelefonia", targetNamespace = "http://matriz.linenumber.claro.co.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceMatrizTelefonia {


    /**
     * 
     * @param data
     * @return
     *     returns com.co.claro.linenumber.matriz.Resultado
     * @throws ProtocolException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "matriztelefonia", targetNamespace = "http://matriz.linenumber.claro.co.com/", className = "com.co.claro.linenumber.matriz.Matriztelefonia")
    @ResponseWrapper(localName = "matriztelefoniaResponse", targetNamespace = "http://matriz.linenumber.claro.co.com/", className = "com.co.claro.linenumber.matriz.MatriztelefoniaResponse")
    @Action(input = "http://matriz.linenumber.claro.co.com/WebServiceMatrizTelefonia/matriztelefoniaRequest", output = "http://matriz.linenumber.claro.co.com/WebServiceMatrizTelefonia/matriztelefoniaResponse", fault = {
        @FaultAction(className = ProtocolException_Exception.class, value = "http://matriz.linenumber.claro.co.com/WebServiceMatrizTelefonia/matriztelefonia/Fault/ProtocolException"),
        @FaultAction(className = IOException_Exception.class, value = "http://matriz.linenumber.claro.co.com/WebServiceMatrizTelefonia/matriztelefonia/Fault/IOException")
    })
    public Resultado matriztelefonia(
        @WebParam(name = "data", targetNamespace = "")
        String data)
        throws IOException_Exception, ProtocolException_Exception
    ;

}
